'A Roadmap for Programming Beginners
'Based on PlantUML Activity Diagram: https://plantuml.com/activity-diagram-beta
'Text styling: https://plantuml.com/creole
'For image edition and generation, access online PlantText design tool (https://www.planttext.com/) or run PlantUML from command line: java -jar plantuml.jar -tsvg roadmap.puml

@startuml
  title A Roadmap for Programming Beginners

  'Subject color
  !$techcolour = "#Cyan"
  !$metacolour = "#Pink"

  'Procedure for inserting subjects
  !unquoted procedure $subject($name, $urls="", $general="no")

    !$colour="#Cyan"
    !if ($general == "yes")
      !$colour="#Pink"
    !endif

    !if ($urls != "")
      !$urls="\n"+$urls
    !endif

    $colour:<b>$name</b>$urls;

  !endprocedure
  

  'Roadmap beginning
  start

  'Roadmap legend
  floating note right $techcolour
    Programming Concepts
  end note
  floating note right $metacolour
    General Programming Stuff
  end note

  'Subjects
  $subject(Algorithms,\
[[https://www.khanacademy.org/computing/computer-science/algorithms#intro-to-algorithms Khan Academy]])
  fork
    $subject(Basic Input/Output,\
[[https://codelikethis.com/lessons/javascript/input-and-output Code like this]])
  fork again
    $subject(Variables,\
[[https://www.khanacademy.org/computing/ap-computer-science-principles/programming-101/storing-variables/a/assigning-variables Khan Academy]])
  fork again
    $subject(Basic Types,\
[[https://en.wikipedia.org/wiki/Data_type Wikipedia]]\n\
[[https://www.tutorialspoint.com/computer_programming/computer_programming_data_types.htm TutorialsPoint]]\n\
[[https://en.wikiversity.org/wiki/Types_and_variables Wikiversity]])
  fork again
    $subject(Naming Convention,\
[[https://en.wikipedia.org/wiki/Naming_convention_(programming) Wikipedia]]\n\
[[https://devopedia.org/naming-conventions Devopedia]]\n\
[[https://dmitripavlutin.com/coding-like-shakespeare-practical-function-naming-conventions/ Opinion]], yes)
  fork again
    $subject(Comments,\
[[https://en.wikipedia.org/wiki/Comment_(computer_programming) Wikipedia]], yes)
  endfork
  fork
    $subject(Conditionals,\
[[https://en.wikipedia.org/wiki/Conditional_(computer_programming) Wikipedia]])
  fork again
    $subject(Indentation,\
[[https://developers.slashdot.org/story/20/06/20/0358229/david-heinemeier-hansson-explains-what-it-takes-to-write-great-code Opinion]], yes)
  endfork
  fork
    $subject(Loops,\
[[https://www.tutorialspoint.com/computer_programming/computer_programming_loops.htm TutorialsPoint]])
  fork again
    $subject(Arrays,\
[[https://en.wikipedia.org/wiki/Array_programming Wikipedia]]\n\
[[https://www.tutorialspoint.com/computer_programming/computer_programming_arrays.htm TutorialsPoint]])
    $subject(Matrices,\
[[https://www.geeksforgeeks.org/matrix/ Geeks4Geeks]])
  fork again
    $subject(User Defined Data Type,\
[[https://learnlearn.uk/alevelcs/user-defined-types/ Access 2 Learn]])
  endfork
  fork
    $subject(Functions,\
[[https://computersciencewiki.org/index.php/Functions CS Wiki]]\n\
[[https://eloquentjavascript.net/03_functions.html JS Book]])
    $subject(Macros,\
[[https://en.m.wikipedia.org/wiki/Macro_(computer_science) Wikipedia]])
  fork again
    $subject(Parameter Passing,\
[[https://en.wikipedia.org/wiki/Parameter_(computer_programming) Wikipedia]])
  fork again
    $subject(Scope,\
[[https://en.wikipedia.org/wiki/Scope_(computer_science) Wikipedia]]\n\
[[https://en.wikiversity.org/wiki/Introduction_to_Programming/Scope Wikiversity]])
  endfork
  fork
    $subject(Recursion,\
[[https://en.wikipedia.org/wiki/Recursion_(computer_science) Wikipedia]]\n\
[[https://www.khanacademy.org/computing/computer-science/algorithms#recursive-algorithms Khan Academy]])
  fork again
    $subject(Dynamic Allocation,\
[[https://www.geeksforgeeks.org/what-is-dynamic-memory-allocation/ Geeks4Geeks Article]])
  fork again
    $subject(Sorting and Searching Algorithms,\
[[https://visualgo.net/en]]\n\
[[https://www.khanacademy.org/computing/computer-science/algorithms/sorting-algorithms/a/sorting Khan Academy]])
  fork again
    $subject(Debug,\
[[https://en.wikipedia.org/wiki/Debugging Wikipedia]], yes)
  endfork
  fork
    $subject(Files Input/Output,\
[[https://www.tutorialspoint.com/computer_programming/computer_programming_file_io.htm TutorialsPoint]])
  fork again
    $subject(Exception Handling,\
[[https://en.wikipedia.org/wiki/Exception_handling Wikipedia]])
  endfork
  $subject(Lists/Stacks/Trees/Graphs,\
[[https://visualgo.net/en]])
  $subject(Generic Programming,\
[[https://en.wikipedia.org/wiki/Generic_programming Wikipedia]]\n\
[[https://stackoverflow.com/tags/generic-programming StackOverflow]])
  fork
    $subject(Abstract Data Types,\
[[https://en.wikipedia.org/wiki/Data_type#Abstract_data_types Wikipedia]])
  fork again 
    $subject(APIs,\
[[https://carlosbazilio.github.io/livros/programandonacozinha/conceitos-avancados/apis.html Analogy]]\n\
[[https://en.wikipedia.org/wiki/API Wikipedia]])
  fork again 
    $subject(Documentation,\
[[https://www.doxygen.nl/index.html Tool]], yes) 
  endfork 
  fork 
    $subject(Libraries,\
[[https://en.wikipedia.org/wiki/Library_(computing) Wikipedia]]\n\
[[https://devopedia.org/standard-library Devopedia]])
  fork again 
    $subject(Versioning,\
[[https://access2learn.com/classwork/programming-languages/what-is-source-control/ Access 2 Learn]]\n\
[[https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control Introduction]], yes)
  endfork 
  $subject(Dictionaries,\
[[https://en.wikipedia.org/wiki/Associative_array Wikipedia]]\n\
[[https://en.wikibooks.org/wiki/A-level_Computing/AQA/Paper_1/Fundamentals_of_data_structures/Dictionaries Wiki Book]])
  $subject(Iterators,\
[[https://www.alura.com.br/artigos/o-que-sao-iteradores-no-python Alura Article]])
  $subject(Regular Expressions,\
[[https://en.wikipedia.org/wiki/Regular_expression Wikipedia]]\n\
[[https://eloquentjavascript.net/09_regexp.html eloquentjavascript]]\n\
[[https://regexr.com/ Playground]]\n\
[[https://regex101.com/ Playground2]])
  fork
    $subject(GUI Programming,\
[[https://www.geeksforgeeks.org/python-gui-tkinter/ Geeks4Geeks Article]])
  fork again
    $subject(Functional Programming,\
[[http://learnyouahaskell.com/ Haskell Book]])
  fork again 
    $subject(Object Oriented Programming,\
[[https://www.youtube.com/watch?v=oWVQEru_1M4 Video (in Portuguese)]])
  fork again
    $subject(Coroutine,\
[[https://en.wikipedia.org/wiki/Coroutine Wikipedia]]\n\
[[https://www.lua.org/pil/9.html Lua Book]])
    $subject(Concurrent Programming,\
[[https://thecomputersciencebook.com/book/concurrent-programming/#leanpub-auto-concurrent-programming The Comp. Science Book]])
  fork again 
    $subject(Logic Programming,\
[[https://eecs390.github.io/notes/declarative.html Michigan Course]])
  fork again
    $subject(Network Programming,\
[[https://csharp-networking.com/ C# Networking Book]])
  endfork
  $subject(Patterns,\
[[https://refactoring.guru/design-patterns GoF Patterns]])
  $subject(Frameworks,\
[[http://www2.ic.uff.br/~bazilio/programandonacozinha/conceitos-avancados/frameworks.html Analogy (in Portuguese)]])
  $subject(And so on ...)
@enduml